services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    ports:
      - "5540:5540"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"