# Generated by Django 6.0.1 on 2026-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        ('groups', '0002_alter_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='groups.group'),
        ),
    ]
