# Generated by Django 6.0.1 on 2026-03-31 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
        ('groups', '0004_post'),
        ('interactions', '0002_comment_post_like_comment_like_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'artwork'), name='unique_user_artwork_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artwork__isnull', False), ('comment__isnull', True), ('post__isnull', True)), models.Q(('artwork__isnull', True), ('comment__isnull', True), ('post__isnull', False)), models.Q(('artwork__isnull', True), ('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='like_target_constraint'),
        ),
    ]
