# Generated by Django 6.0.1 on 2026-02-10 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('owner', 'name')},
        ),
    ]
