# Generated by Django 6.0.1 on 2026-04-01 15:10
from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ArtHubUser = apps.get_model('accounts', 'ArtHubUser')

    moderators_group, _ = Group.objects.get_or_create(name='Content Moderator')
    editors_group, _ = Group.objects.get_or_create(name='Content Editor')

    editors_permissions = [
        ('artworks', 'change_artwork'),
        ('albums', 'change_album'),
        ('interactions', 'change_comment'),
        ('groups', 'change_post'),
        ('groups', 'change_group')
    ]

    moderators_permissions = [
        ('accounts', 'delete_arthubuser'),
        ('accounts', 'delete_profile'),
        ('artworks', 'delete_artwork'),
        ('albums', 'delete_album'),
        ('interactions', 'delete_comment'),
        ('groups', 'delete_post'),
        ('groups', 'delete_group'),
    ]

    for app_label, codename in editors_permissions:
        try:
            perm = Permission.objects.get(codename=codename, content_type__app_label=app_label)
            editors_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass

    for app_label, codename in moderators_permissions:
        try:
            perm = Permission.objects.get(codename=codename, content_type__app_label=app_label)
            moderators_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass

    try:
        alice = ArtHubUser.objects.get(username='alice')
        alice.groups.add(editors_group)
        alice.groups.add(moderators_group)
    except ArtHubUser.DoesNotExist:
        pass

    try:
        dave = ArtHubUser.objects.get(username='dave')
        dave.groups.add(editors_group)
    except ArtHubUser.DoesNotExist:
        pass

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    ArtHubUser = apps.get_model('accounts', 'ArtHubUser')

    moderators_group = Group.objects.filter(name='Content Moderator').first()
    editors_group = Group.objects.filter(name='Content Editor').first()

    try:
        alice = ArtHubUser.objects.get(username='alice')
        if editors_group:
            alice.groups.remove(editors_group)
        if moderators_group:
            alice.groups.remove(moderators_group)
    except ArtHubUser.DoesNotExist:
        pass

    try:
        dave = ArtHubUser.objects.get(username='dave')
        if editors_group:
            dave.groups.remove(editors_group)
    except ArtHubUser.DoesNotExist:
        pass

    Group.objects.filter(name__in=['Content Moderator', 'Content Editor']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('albums', '0002_initial'),
        ('artworks', '0002_initial'),
        ('groups', '0001_initial'),
        ('interactions', '0001_initial'),
        ('common', '0001_seed_initial_data'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
