# Generated by Django 6.0.1 on 2026-03-24 16:58
from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    moderators_group, _ = Group.objects.get_or_create(name='Content Moderator')
    editors_group, _ = Group.objects.get_or_create(name='Content Editor')

    change_group_perm = Permission.objects.get(
        codename='change_group',
        content_type__app_label='groups'
    )

    delete_group_perm = Permission.objects.get(
        codename='delete_group',
        content_type__app_label='groups'
    )

    editors_permissions = [
        'change_artwork',
        'change_album',
        'change_comment',
        'change_post'
    ]

    moderators_permissions = [
        'delete_arthubuser',
        'delete_profile',
        'delete_artwork',
        'delete_album',
        'delete_comment',
        'delete_post'
    ]

    for codename in editors_permissions:
        try:
            perm = Permission.objects.get(codename=codename)
            editors_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass

    editors_group.permissions.add(change_group_perm)

    for codename in moderators_permissions:
        try:
            perm = Permission.objects.get(codename=codename)
            moderators_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass

    moderators_group.permissions.add(delete_group_perm)

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Content Moderator', 'Content Editor']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artworks', '0001_initial'),
        ('albums', '0001_initial'),
        ('groups', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
