# Generated by Django 6.0.1 on 2026-03-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arthubuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user-avatars/'),
        ),
        migrations.AddField(
            model_name='arthubuser',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='user-backgrounds/'),
        ),
        migrations.AddField(
            model_name='arthubuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='user-banners/'),
        ),
    ]
