# Generated by Django 6.0.1 on 2026-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfolder',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='group_folders', to='artworks.artwork'),
        ),
    ]
