# Generated by Django 6.0.1 on 2026-03-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupfolder_artworks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsubmission',
            unique_together=set(),
        ),
    ]
