# Generated by Django 6.0.1 on 2026-04-01 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('groups', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('join_public_group', 'Join Public Group'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('submission', 'Artwork Submission'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('like_artwork', 'Like Artwork'), ('like_comment', 'Like Comment'), ('like_post', 'Like Post'), ('comment_artwork', 'Comment Artwork'), ('comment_post', 'Comment Post'), ('reply', 'Reply to Comment'), ('new_post', 'New Post in Group')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
