# Generated by Django 6.0.1 on 2026-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_type_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_public_group', 'Join Public Group'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('submission', 'Artwork Submission'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('like_artwork', 'Like Artwork'), ('like_comment', 'Like Comment'), ('like_post', 'Like Post'), ('comment_artwork', 'Comment Artwork'), ('comment_post', 'Comment Post'), ('reply', 'Reply to Comment'), ('new_post', 'New Post in Group')], max_length=50),
        ),
    ]
